steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '${WORKSPACE}/mta.jar'
  neoDeploy:
    neoHome: '${WORKSPACE}/neo-java-web-sdk/'
    neo:
      credentialsId: 'b5dfe66b-8871-479f-9334-bcd8324e25f1'
      account: 'p2001350607trial'
      host: 'hanatrial.ondemand.com'
